"""course_languages

Revision ID: 0a05f8c783ca
Revises: 50e0d17480f9
Create Date: 2025-03-18 01:59:38.002894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0a05f8c783ca'
down_revision: Union[str, None] = '50e0d17480f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('languages', sa.VARCHAR(length=10), nullable=False, default="vi"))
        batch_op.drop_index('ix_course_language')
        batch_op.create_index('ix_course_languages', ['languages'], unique=False)
        batch_op.drop_column('language')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.VARCHAR(length=10), nullable=False))
        batch_op.drop_index('ix_course_languages')
        batch_op.create_index('ix_course_language', ['language'], unique=False)
        batch_op.drop_column('languages')
    # ### end Alembic commands ###
