"""course_category

Revision ID: 50e0d17480f9
Revises: 77546603f312
Create Date: 2025-03-17 23:42:43.749010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '50e0d17480f9'
down_revision: Union[str, None] = '77546603f312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_table('coursecategorylink',
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'category_id')
    )
    op.create_index(op.f('ix_coursecategorylink_category_id'), 'coursecategorylink', ['category_id'], unique=False)
    op.create_index(op.f('ix_coursecategorylink_course_id'), 'coursecategorylink', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_language'), 'course', ['language'], unique=False)
    op.create_index(op.f('ix_course_level'), 'course', ['level'], unique=False)
    op.create_index(op.f('ix_course_price'), 'course', ['price'], unique=False)
    op.create_index(op.f('ix_course_title'), 'course', ['title'], unique=False)
    op.drop_column('course', 'category')
    op.drop_index('ix_user_avatar', table_name='user')
    op.drop_index('ix_user_avatar_content_type', table_name='user')
    op.drop_index('ix_user_bio', table_name='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_bio', 'user', ['bio'], unique=False)
    op.create_index('ix_user_avatar_content_type', 'user', ['avatar_content_type'], unique=False)
    op.create_index('ix_user_avatar', 'user', ['avatar'], unique=False)
    op.add_column('course', sa.Column('category', sa.VARCHAR(length=100), nullable=False))
    op.drop_index(op.f('ix_course_title'), table_name='course')
    op.drop_index(op.f('ix_course_price'), table_name='course')
    op.drop_index(op.f('ix_course_level'), table_name='course')
    op.drop_index(op.f('ix_course_language'), table_name='course')
    op.drop_index(op.f('ix_coursecategorylink_course_id'), table_name='coursecategorylink')
    op.drop_index(op.f('ix_coursecategorylink_category_id'), table_name='coursecategorylink')
    op.drop_table('coursecategorylink')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
