"""section_title

Revision ID: 60e4b8670e95
Revises: b03561a02d62
Create Date: 2025-04-20 22:47:01.870411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '60e4b8670e95'
down_revision: Union[str, None] = 'b03561a02d62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('section_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index('ix_section_sectionTitle', table_name='section')
    op.create_index(op.f('ix_section_section_title'), 'section', ['section_title'], unique=False)
    op.drop_column('section', 'sectionTitle')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('sectionTitle', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_section_section_title'), table_name='section')
    op.create_index('ix_section_sectionTitle', 'section', ['sectionTitle'], unique=False)
    op.drop_column('section', 'section_title')
    # ### end Alembic commands ###
