"""lesson_resource

Revision ID: 8fa03b0c4391
Revises: 989b3164454a
Create Date: 2025-04-17 19:20:30.901272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8fa03b0c4391'
down_revision: Union[str, None] = '989b3164454a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessonresource',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lesson_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('title')
    )
    op.create_index(op.f('ix_lessonresource_lesson_id'), 'lessonresource', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lessonresource_title'), 'lessonresource', ['title'], unique=False)
    op.add_column('lesson', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True, default='video'))
    op.add_column('lesson', sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_lesson_type'), 'lesson', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_type'), table_name='lesson')
    op.drop_column('lesson', 'text')
    op.drop_column('lesson', 'type')
    op.drop_index(op.f('ix_lessonresource_title'), table_name='lessonresource')
    op.drop_index(op.f('ix_lessonresource_lesson_id'), table_name='lessonresource')
    op.drop_table('lessonresource')
    # ### end Alembic commands ###
