"""quiz

Revision ID: b03561a02d62
Revises: fa3548db92a2
Create Date: 2025-04-20 22:40:36.959059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b03561a02d62'
down_revision: Union[str, None] = 'fa3548db92a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_in_section', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_id'), 'quiz', ['id'], unique=False)
    op.create_index(op.f('ix_quiz_order_in_section'), 'quiz', ['order_in_section'], unique=False)
    op.create_index(op.f('ix_quiz_section_id'), 'quiz', ['section_id'], unique=False)
    op.create_index(op.f('ix_quiz_title'), 'quiz', ['title'], unique=False)
    op.create_table('quizquestion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('options', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('correct_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quiz_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizquestion_id'), 'quizquestion', ['id'], unique=False)
    op.create_index(op.f('ix_quizquestion_question_name'), 'quizquestion', ['question_name'], unique=False)
    op.create_index(op.f('ix_quizquestion_quiz_id'), 'quizquestion', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quizquestion_type'), 'quizquestion', ['type'], unique=False)
    op.add_column('lesson', sa.Column('order_in_section', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_lesson_order_in_section'), 'lesson', ['order_in_section'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_order_in_section'), table_name='lesson')
    op.drop_column('lesson', 'order_in_section')
    op.drop_index(op.f('ix_quizquestion_type'), table_name='quizquestion')
    op.drop_index(op.f('ix_quizquestion_quiz_id'), table_name='quizquestion')
    op.drop_index(op.f('ix_quizquestion_question_name'), table_name='quizquestion')
    op.drop_table('quizquestion')
    op.drop_index(op.f('ix_quiz_title'), table_name='quiz')
    op.drop_index(op.f('ix_quiz_section_id'), table_name='quiz')
    op.drop_index(op.f('ix_quiz_order_in_section'), table_name='quiz')
    op.drop_index(op.f('ix_quiz_id'), table_name='quiz')
    op.drop_table('quiz')
    # ### end Alembic commands ###
