"""courses_thumbnail

Revision ID: d64635f505d9
Revises: 94b78ac485cd
Create Date: 2025-03-28 00:37:35.919985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd64635f505d9'
down_revision: Union[str, None] = '94b78ac485cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('thumbnail', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('user', 'avatar_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_link', sa.VARCHAR(), nullable=True))
    op.drop_column('user', 'avatar')
    op.drop_column('course', 'thumbnail')
    # ### end Alembic commands ###
