"""language

Revision ID: e8cf91be1d13
Revises: d64635f505d9
Create Date: 2025-03-31 21:08:09.597817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e8cf91be1d13'
down_revision: Union[str, None] = 'd64635f505d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False, server_default="vi"))
    op.drop_index('ix_course_languages', table_name='course')
    op.create_index(op.f('ix_course_language'), 'course', ['language'], unique=False)
    op.drop_column('course', 'languages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('languages', sa.VARCHAR(length=10), nullable=False))
    op.drop_index(op.f('ix_course_language'), table_name='course')
    op.create_index('ix_course_languages', 'course', ['languages'], unique=False)
    op.drop_column('course', 'language')
    # ### end Alembic commands ###
